import 'models/movie_model.dart';

final dummyMovies = [
  MovieModel(
      adult: false,
      backdropPath: "/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
      genreIds: [28, 878, 12],
      id: 588228,
      originalLanguage: 'en',
      originalTitle: "The Tomorrow War",
      overview:
          "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",
      popularity: 4564.402,
      posterPath: '/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg',
      releaseDate: '2021-09-03',
      title: "The Tomorrow War",
      video: false,
      voteAverage: 8,
      voteCount: 199),
  MovieModel(
      adult: false,
      backdropPath: "/nDLylQOoIazGyYuWhk21Yww5FCb.jpg",
      genreIds: [28, 12, 14],
      id: 566525,
      originalLanguage: "en",
      originalTitle: "Shang-Chi and the Legend of the Ten Rings",
      overview:
          "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
      popularity: 3557.631,
      posterPath: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
      releaseDate: "2021-09-01",
      title: "Shang-Chi and the Legend of the Ten Rings",
      video: false,
      voteAverage: 8,
      voteCount: 326),
  MovieModel(
      adult: false,
      backdropPath: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
      genreIds: [28, 12, 14, 35],
      id: 436969,
      originalLanguage: "en",
      originalTitle: "The Suicide Squad",
      overview:
          "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
      popularity: 3473.331,
      posterPath: "/iXbWpCkIauBMStSTUT9v4GXvdgH.jpg",
      releaseDate: "2021-07-28",
      title: "The Suicide Squad",
      video: false,
      voteAverage: 8,
      voteCount: 3463),
  MovieModel(
      adult: false,
      backdropPath: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
      genreIds: [12, 14, 35, 28],
      id: 451048,
      originalLanguage: "en",
      originalTitle: "Jungle Cruise",
      overview:
          "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
      popularity: 3034.948,
      posterPath: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
      releaseDate: "2021-07-28",
      title: "Jungle Cruise",
      video: false,
      voteAverage: 7.9,
      voteCount: 2377),
  MovieModel(
      adult: false,
      backdropPath: "/nprqOIEfiMMQx16lgKeLf3rmPrR.jpg",
      genreIds: [28, 53, 18],
      id: 619297,
      originalLanguage: "en",
      originalTitle: "Sweet Girl",
      overview:
          "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
      popularity: 2455.96,
      posterPath: "/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
      releaseDate: "2021-08-18",
      title: "Sweet Girl",
      video: false,
      voteAverage: 6.9,
      voteCount: 442),
  MovieModel(
      adult: false,
      backdropPath: "/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg",
      genreIds: [53, 27],
      id: 482373,
      originalLanguage: "en",
      originalTitle: "Don't Breathe 2",
      overview:
          "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.",
      popularity: 2373.928,
      posterPath: "/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg",
      releaseDate: "2021-08-12",
      title: "Don't Breathe 2",
      video: false,
      voteAverage: 7.6,
      voteCount: 265),
  MovieModel(
      adult: false,
      backdropPath: "/mtRW6eAwOO27h3zrfU2foQFW7Hg.jpg",
      genreIds: [16, 10751, 12, 35],
      id: 675445,
      originalLanguage: "en",
      originalTitle: "PAW Patrol: The MovieModel",
      overview:
          "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.",
      popularity: 2373.203,
      posterPath: "/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
      releaseDate: "2021-08-09",
      title: "PAW Patrol: The MovieModel",
      video: false,
      voteAverage: 8,
      voteCount: 342),
  MovieModel(
      adult: false,
      backdropPath: "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
      genreIds: [28, 12, 53, 878],
      id: 497698,
      originalLanguage: "en",
      originalTitle: "Black Widow",
      overview:
          "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
      popularity: 2310.483,
      posterPath: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
      releaseDate: "2021-07-07",
      title: "Black Widow",
      video: false,
      voteAverage: 7.8,
      voteCount: 4749),
  MovieModel(
      adult: false,
      backdropPath: "/8s4h9friP6Ci3adRGahHARVd76E.jpg",
      genreIds: [16, 35, 10751, 878],
      id: 379686,
      originalLanguage: "en",
      originalTitle: "Space Jam: A New Legacy",
      overview:
          "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
      popularity: 2153.851,
      posterPath: "/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
      releaseDate: "2021-07-08",
      title: "Space Jam: A New Legacy",
      video: false,
      voteAverage: 7.4,
      voteCount: 2070),
  MovieModel(
      adult: false,
      backdropPath: "/j28p5VwI5ieZnNwfeuZ5Ve3mPsn.jpg",
      genreIds: [35, 28, 12, 878],
      id: 550988,
      originalLanguage: "en",
      originalTitle: "Free Guy",
      overview:
          "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
      popularity: 2070.861,
      posterPath: "/yc2IfL701hGkNHRgzmF4C6VKO14.jpg",
      releaseDate: "2021-08-11",
      title: "Free Guy",
      video: false,
      voteAverage: 7.8,
      voteCount: 556),
  MovieModel(
      adult: false,
      backdropPath: "/1Txzm4bY5ZDqvgMl7MmHeBMl7HH.jpg",
      genreIds: [80, 18, 53],
      id: 860425,
      originalLanguage: "es",
      originalTitle: "Sinaliento",
      overview: "",
      popularity: 1940.775,
      posterPath: "/oxNoVgbu2v9ETL93Kri1pw8osYf.jpg",
      releaseDate: "2021-08-11",
      title: "Breathless",
      video: false,
      voteAverage: 6.9,
      voteCount: 17),
  MovieModel(
      adult: false,
      backdropPath: "/AjQgFtfXTmmMVuaH2VfQDdGbeQH.jpg",
      genreIds: [28, 18, 80],
      id: 706972,
      originalLanguage: "en",
      originalTitle: "Narco Sub",
      overview:
          "A man will become a criminal to save his family.  Director: Shawn Welling  Writer: Derek H. Potts  Stars: Tom Vera, Tom Sizemore, Lee Majors |",
      popularity: 1882.401,
      posterPath: "/7p0O4mKYLIhU2E5Zcq9Z3vOZ4e9.jpg",
      releaseDate: "2021-07-22",
      title: "Narco Sub",
      video: false,
      voteAverage: 7.1,
      voteCount: 45),
  MovieModel(
      adult: false,
      backdropPath: "/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg",
      genreIds: [10749, 18],
      id: 744275,
      originalLanguage: "en",
      originalTitle: "After We Fell",
      overview:
          "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
      popularity: 1772.505,
      posterPath: "/92wWZAzHPrvEKSpIJxGeMmImHOf.jpg",
      releaseDate: "2021-09-01",
      title: "After We Fell",
      video: false,
      voteAverage: 8.8,
      voteCount: 167),
  MovieModel(
      adult: false,
      backdropPath: "/uZDE9VnKFnIPmWriMjnp82bH9S8.jpg",
      genreIds: [28, 53],
      id: 825997,
      originalLanguage: "en",
      originalTitle: "Rogue Hostage",
      overview:
          "A former Marine races against time to save a group of hostages -- including his young daughter and a congressman — when armed militants take over his stepfather's store.",
      popularity: 1672.497,
      posterPath: "/1ho7YYp1DvCke9I1D3Olbh2Px63.jpg",
      releaseDate: "2021-06-11",
      title: "Rogue Hostage",
      video: false,
      voteAverage: 6.7,
      voteCount: 70),
  MovieModel(
      adult: false,
      backdropPath: "/uHmvk8FnoxpgujDU0RIXLkv2fNt.jpg",
      genreIds: [16, 35],
      id: 573164,
      originalLanguage: "es",
      originalTitle: "Un rescate de huevitos",
      overview:
          "A rooster and his fowl partner embark on a dangerous trip to the Congo to recover their stolen eggs from a group of Russian goons.",
      popularity: 1665.906,
      posterPath: "/wrlQnKHLCBheXMNWotyr5cVDqNM.jpg",
      releaseDate: "2021-08-12",
      title: "Eggs Run",
      video: false,
      voteAverage: 8.4,
      voteCount: 200),
  MovieModel(
      adult: false,
      backdropPath: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
      genreIds: [28, 80, 53],
      id: 385128,
      originalLanguage: "en",
      originalTitle: "F9",
      overview:
          "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      popularity: 1653.145,
      posterPath: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      releaseDate: "2021-05-19",
      title: "F9",
      video: false,
      voteAverage: 7.5,
      voteCount: 3407),
  MovieModel(
      adult: false,
      backdropPath: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
      genreIds: [878, 28, 53],
      id: 581726,
      originalLanguage: "en",
      originalTitle: "Infinite",
      overview:
          "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
      popularity: 1508.399,
      posterPath: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
      releaseDate: "2021-06-10",
      title: "Infinite",
      video: false,
      voteAverage: 7.5,
      voteCount: 947),
  MovieModel(
      adult: false,
      backdropPath: "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
      genreIds: [16, 35, 10751, 14],
      id: 508943,
      originalLanguage: "en",
      originalTitle: "Luca",
      overview:
          "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
      popularity: 1500.254,
      posterPath: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
      releaseDate: "2021-06-17",
      title: "Luca",
      video: false,
      voteAverage: 8.1,
      voteCount: 4304),
  MovieModel(
      adult: false,
      backdropPath: "/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg",
      genreIds: [
        16,
        35,
        12,
        10751,
      ],
      id: 459151,
      originalLanguage: "en",
      originalTitle: "The Boss Baby: Family Business",
      overview:
          "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
      popularity: 1484.604,
      posterPath: "/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
      releaseDate: "2021-07-01",
      title: "The Boss Baby: Family Business",
      video: false,
      voteAverage: 7.8,
      voteCount: 1323),
  MovieModel(
      adult: false,
      backdropPath: "/o0UGl6icA4DbhmDNgdZ5AWvuTtM.jpg",
      genreIds: [35],
      id: 653349,
      originalLanguage: "en",
      originalTitle: "Vacation Friends",
      overview:
          "When a straight-laced couple that has fun with a rowdy couple on vacation in Mexico return to the States, they discover that the crazy couple they met in Mexico followed them back home and decide to play tricks on them.",
      popularity: 1403.482,
      posterPath: "/uTgZuqUQbaCB6Wfk03N8IUEuzQf.jpg",
      releaseDate: "2021-08-27",
      title: "Vacation Friends",
      video: false,
      voteAverage: 7.6,
      voteCount: 162),
];
